version: "3"

services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    volumes:
      - /opt/data/apps/${ELASTIC_NAME}/certs:/usr/share/elasticsearch/config/certs
      - /opt/data/apps:/opt/data/apps
    user: "0"
    environment:
      - ELASTIC_NAME=${ELASTIC_NAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWD}
      - KIBANA_PASSWD=${KIBANA_PASSWD}
    command: >
      bash /opt/data/apps/es/init_certs.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/ca.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - 'devops'

  elastic:
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    hostname: ${ELASTIC_NAME}
    container_name: ${ELASTIC_NAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/data/apps/${ELASTIC_NAME}/certs:/usr/share/elasticsearch/config/certs
      - /opt/data/apps/${ELASTIC_NAME}/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    user: "0"
    environment:
      - node.name=${ELASTIC_NAME}
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=${ELASTIC_MASTER}
      - discovery.seed_hosts=${ELASTIC_SEED}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/${ELASTIC_NAME}.key
      - xpack.security.http.ssl.certificate=certs/${ELASTIC_NAME}.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/${ELASTIC_NAME}.key
      - xpack.security.transport.ssl.certificate=certs/${ELASTIC_NAME}.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - "${ELASTIC_JAVA}"
    # mem_limit: 1G
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - 'devops'
networks:
  devops:
    external: true  