version: '3'
services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - /opt/data/apps/redis/datadir:/data
      - /opt/data/apps/redis/redis.conf:/etc/redis.conf
      # - ./logs:/logs
    command:
      /bin/bash -c "echo 511 > /proc/sys/net/core/somaxconn
      && echo never > /sys/kernel/mm/transparent_hugepage/enabled
      && redis-server /etc/redis.conf"
    ports:
      - 6379:6379