version: '3'
services:
  setup:
    image: elasticsearch:7.5.1
    volumes:
      - /opt/data/apps:/opt/data/apps
    user: "0"
    command: >
      bash -c '
        mkdir -p /opt/data/apps/skywalking/esdata
        chown -R 1000:1000 /opt/data/apps/skywalking/esdata
        until curl -s http://skyes7:9200 | grep -q "skywalking-es7"; do sleep 30; done;
        '
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/data/apps/skywalking/esdata ]"]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - 'devops' 
    
  skyes7:
    container_name: skywalking-es7
    hostname: skywalking-es7
    image: elasticsearch:7.5.1
    restart: always
    volumes:
      - /opt/data/apps/skywalking/esdata:/usr/share/elasticsearch/data
    networks:
      - 'devops' 
    environment:
      - discovery.type=single-node
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'skywalking-es7'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es-hq:
    container_name: skywalking-es-hq
    hostname: skywalking-es-hq
    image: elastichq/elasticsearch-hq 
    restart: always
    ports:
      - '5000:5000'
    networks:
      - 'devops' 
    depends_on:
      skyes7:
        condition: service_healthy

  skyoap:
    container_name: skywalking-oap
    hostname: skywalking-oap 
    image: apache/skywalking-oap-server:8.7.0-es7
    ports:
      - "11800:11800"
      - "12800:12800"
      - "5005:5005"
    networks:
      - 'devops'
    restart: on-failure
    environment:
      - SW_STORAGE=elasticsearch7
      - SW_STORAGE_ES_CLUSTER_NODES="skyes7:9200"
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -zn 127.0.0.1 11800"]
      interval: 5s
      timeout: 60s
      retries: 120
    depends_on:
      skyes7:
        condition: service_healthy

  skywalking-ui:
    container_name: skywalking-ui
    hostname: skywalking-ui
    image: apache/skywalking-ui:8.7.0
    restart: always
    ports:
      - "8080:8080"
    networks:
      - 'devops'
    environment:
      - SW_OAP_ADDRESS=http://skyoap:12800
    depends_on:
      skyoap:
        condition: service_healthy
         
networks:
  devops:
    external: true