version: '3.5'
services:        
 zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
  ports:
   - "80:8080"
   - "443:8443"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
  #  - /opt/data/apps/zabbix-nginx/etc/ssl/nginx:/etc/ssl/nginx:ro
  #  - /opt/data/apps/zabbix-nginx/modules/:/usr/share/zabbix/modules/:ro
  environment:
    # MYSQL 服务器IP
    - DB_SERVER_HOST=mysql-server
    - MYSQL_DATABASE=zabbix
    # MYSQL root 密码
    - MYSQL_ROOT_PASSWORD=Rokin@2022
    - MYSQL_USER=zabbix
    # MYSQL zabbix 密码
    - MYSQL_PASSWORD=Rokin@2022
    # MYSQL zabbix 服务器IP
    - ZBX_SERVER_HOST=zabbix-server
    - ZBX_SERVER_NAME=zabbix-server
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8080/"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 30s
  networks:
    - 'devops'
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

networks:
  devops:
    external: true  
